name: Test .NET Version

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run daily at 6:00 AM UTC to check for new .NET versions
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  test-dotnet-version:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET 10.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      
      # Verify the installed .NET SDK version
      - name: Verify .NET 10.0.x Installation
        run: dotnet --version

      - name: Display .NET Info
        run: dotnet --info

      - name: List installed .NET SDKs
        run: dotnet --list-sdks

      - name: List installed .NET runtimes
        run: dotnet --list-runtimes

      - name: Create and test a simple console application
        run: |
          dotnet new console -n TestApp --force
          cd TestApp
          dotnet run